### ISSUE TITLE
Improve tabline colors

### ISSUE THREAD

**Issue by panosl** [Luxed/ayu-vim#5] opened 2021-03-26 08:45 UTC
Please apply PR https://github.com/ayu-theme/ayu-vim/pull/55 by @stsewd

**Comment by Luxed** [comment] 2021-04-10 00:55
@panosl Sorry for the late reply, I did not get notified for some reason.
Since I do not use this tabline, it would be useful for me to have a simple example.
I thought I fixed it, but I also might have broken it at the same time. Could you give me a minimal vim config as well as screenshots describing what the issue is?

**Comment by panosl** [comment] 2021-04-10 18:32
Here are the screenshots with explanations:
![Screenshot 2021-04-10 at 9 24 25 PM](https://user-images.githubusercontent.com/91211/114280879-02c74700-9a44-11eb-8ba4-e9807fa1681c.png)
![Screenshot 2021-04-10 at 9 22 51 PM](https://user-images.githubusercontent.com/91211/114280880-03f87400-9a44-11eb-8271-24bf62edfe88.png)

you can see the PR https://github.com/ayu-theme/ayu-vim/pull/55 has a much more subtle and clean feel.

**Comment by Luxed** [comment] 2021-06-19 22:42
I have made a Pull Request (finally). Could you please test it and tell me if it is good enough for you?

**Comment by panosl** [comment] 2021-06-20 12:20
> I have made a Pull Request (finally). Could you please test it and tell me if it is good enough for you?

![Screenshot 2021-06-20 at 3 15 33 PM](https://user-images.githubusercontent.com/91211/122673787-c8fc8480-d1da-11eb-99a8-7b66d54fb286.png)

The active ones looks great.

The buffer that currently is not being visible should have the same style as the open buffer IMO.
Isn't the tabline color a bit a bit too dark? Is this the way other ayu editors/IDEs show it?

![Screenshot 2021-06-20 at 3 21 46 PM](https://user-images.githubusercontent.com/91211/122673876-4de79e00-d1db-11eb-8793-8b78c773d2b8.png)

This is the dark variant. Which the tabline color looks even more out of place. We need something more subtle.

**Comment by Luxed** [comment] 2021-12-07 00:55
Hey, I've changed something that should have fixed a bunch of issues with `vim` specifically in commit 9169817. Could you tell me if this is still an issue (without the pull request because I haven't updated it)?

**Comment by willwillsiii** [comment] 2023-03-10 01:50
The tabline colors are much better than shown (and than those in the original repository). I would argue this has been fixed and should be closed.

**Comment by Luxed** [comment] 2023-03-10 02:45
> The tabline colors are much better than shown (and than those in the original repository). I would argue this has been fixed and should be closed.

Thank you for testing! I'll close this as I tested it on my own at some point and it looked fine.

**Closed as completed by Luxed** 2023-03-10 02:45 UTC
