### ISSUE TITLE
Diff colors should be fixed

### ISSUE THREAD

**Issue by carljohnson93** [Luxed/ayu-vim#11] opened 2021-06-19 11:47 UTC
Here's how deleted lines diff color look:

![Снимок экрана 2021-06-19 в 14 45 42](https://user-images.githubusercontent.com/47556468/122641320-38a43e00-d10d-11eb-96a6-c55c3d9e4c74.png)

I expect the color to be red.. Will that be fixed?

**Comment by Luxed** [comment] 2021-06-19 20:17
This is the output I get:
![image](https://user-images.githubusercontent.com/10234894/122654177-8d4cb680-d117-11eb-9677-a55664330b78.png)

Here's the exact steps I did to try and reproduce this issue:
- Create new repo
- Commit new "test" file with contents seen on your _left_ pane.
- Remove the lines and look at the diff using Fugitive's "Gdiffsplit" command.

Can you give more detail on which plugins (if any) you are using?
What steps would I need to do to reproduce this?
Are you _sure_ you are currently using the latest version of my fork?

This looks like the default colors for diff highlights. What does `:hi DiffDelete` give you?

**Comment by carljohnson93** [comment] 2021-06-20 08:29
Oh, indeed, after I removed [rafi/awesome-vim-colorschemes](https://github.com/rafi/awesome-vim-colorschemes) plugin I have similar look, in neovim:

![neovim](https://user-images.githubusercontent.com/47556468/122667259-96429400-d1ba-11eb-9cc4-7f32736fc20f.png)

However, I have some gray bars in vim 8.2

![vim](https://user-images.githubusercontent.com/47556468/122667281-af4b4500-d1ba-11eb-8668-3608bd12262b.png)

Hope it's easy to fix

**Comment by Luxed** [comment] 2021-06-22 13:55
> However, I have some gray bars in vim 8.2
> Hope it's easy to fix

Unfortunately, I don't use vim and I don't even have a working configuration for it (seeing that I fully switched to Neovim with a Lua config).
I will need to request a minimal config to test.
Even then, I really don't see what those might be :/ Maybe a different highlight group?
You also have some padding with the gray bars at the left, but only on your Vim config?
Are you using a terminal?

**Comment by carljohnson93** [comment] 2021-06-24 09:17
My part of config regarding colors and theme:
```vim
set termguicolors

let g:airline_theme = 'ayu'

let ayucolor = 'light'
set background light
colorscheme ayu
```

And yes, I am using terminal.

**Comment by Luxed** [comment] 2021-12-07 00:52
Hey again, I've pushed a fix for another issue that might have fixed your issue. Could you please test again and let me know if this is fixed (especially the grey bars)?

**Comment by willwillsiii** [comment] 2023-03-11 08:57
I've tested -- here are the results:

![image](https://user-images.githubusercontent.com/24965267/224475195-c2050a60-936f-41a9-ab8d-1962c32b0fef.png)

(this fork on left, original repo on right)

Seems fixed! I was never getting the aforementioned grey bars though -- haven't tested on old commits from this fork.

**Closed as completed** 2023-03-14 19:16 UTC
